# Generated by Django 6.0 on 2025-12-14 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_customuser_options_customuser_id_liked_recipes'),
    ]

    operations = [
        migrations.CreateModel(
            name='interactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_recipe', models.IntegerField()),
                ('interaction', models.CharField()),
                ('user', models.ManyToManyField(related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interactions',
            },
        ),
    ]
