# Generated by Django 6.0 on 2025-12-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_interactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id_liked_recipes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Calorie_content',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Carbohydrates',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Cooking_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Count_ingredients',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Fats',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Id_Recipe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Images_recipe',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Ingredients',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Name_recipe',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Number_page',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Pontions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Safes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Squirrels',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Steps_images',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Steps_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Tags',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Type_recipe',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='URL',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Url_images_recipe',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Url_steps_images',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='interactions',
        ),
    ]
