# Generated by Django 6.0 on 2025-12-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_recipereaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Pontions',
            new_name='Portions',
        ),
    ]
