# Generated by Django 6.0 on 2026-01-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_pontions_recipe_portions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_recipes',
            field=models.ManyToManyField(blank=True, related_name='creators', to='myapp.recipe', verbose_name='Созданные рецепты'),
        ),
    ]
